name: CI - Run Tests Before Merge

# Le workflow se déclenche lors de l'ouverture ou de la mise à jour d'une PR vers la branche main
on:
  pull_request:
    branches:
      - main

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: --health-cmd="curl --silent --fail http://localhost:27017" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Wait for MongoDB to be ready
        run: |
          until nc -zv localhost 27017; do
            echo "Waiting for MongoDB to be ready..."
            sleep 2
          done
          echo "MongoDB is ready!"

      - name: Install Backend dependencies
        run: |
          cd ./Backend
          npm install

      - name: Run Backend Tests
        run: |
          cd ./Backend
          npm run test

  # Job pour tester le frontend
  frontend-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]  # Choisissez la version de Node.js que vous utilisez

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Installe les dépendances pour le frontend
      - name: Install Frontend dependencies
        run: |
          cd ./Frontend
          npm install

      # Exécute les tests du frontend
      - name: Run Frontend Tests
        run: |
          cd ./Frontend
          npm run test
